name: pr

on: [pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run yarn lint
              run: |
                  yarn install
                  yarn lint
